# Site settings
title: (Fake) Markov Chains
email: tahnok@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  WARNING: The content contained herein may or may not be sensical. Side effects may include laughter, anger, shallow thoughts, deep thoughts and blindness. Reader discretion is advised
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.tahnok.me" # the base hostname & protocol for your site
permalink: /post/:title.html
code_dir: code_source
paginate: 5

# Build settings
markdown: kramdown
destination: public_html
exclude:
  - deploy.sh
  - Rakefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-gist
  - jekyll-paginate
#   - jekyll-code-example-tag
